language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  include:
    - php: 7.2
      env: SYMFONY_VERSION='4.3.*'
    - php: 7.3
      env: SYMFONY_VERSION='4.4.*'
    - php: 7.4
      env: SYMFONY_VERSION='5.0.*'
  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
  - |
    if [ "$SYMFONY_VERSION" != "" ]; then
      sed -ri 's/"symfony\/(.+)": "(.+)"/"symfony\/\1": "'$SYMFONY_VERSION'"/' composer.json;
    fi;
  - if [ "$DEPENDENCIES" = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
  - composer install --dev

script: vendor/bin/phpunit
